### ISSUE TITLE
可否取消每次打印日志时最后的End()方法？

### ISSUE THREAD

**Issue by sunningcqu** [go-logit/logit#10]
```
logger.Info("info log").End()
logger.Warn("This is a structured message").Any("user", user).Json("userJson", user).End()
```

请问，最后调用End()的这个方法，可以设置为默认调用么？每次都需要用户手动调用的话，着实有点没必要呀
辛苦作者大佬看下这个建议~

**Comment by FishGoddess** [comment]
是的，这个方法每次都需要调用，因为要将缓存数据写出去，并释放缓存。。
不过这个方法确实很烦，我最近一直在想有没有办法可以自动调用，zerolog 里面的是一种办法，不过他们的其实也没有避免，只是换了个名字，看起来更顺眼了。。
后面我可能会更改这个 API 的参数
