### ISSUE TITLE
能加个写日志到文件的示例和文档么？尝试用writer的各种方法一个多小时了还没搞定

### ISSUE THREAD

**Issue by Creky** [go-logit/logit#11]
这真是一次失败的尝试，找到半天没找到写日志到文件的方法，尝试初始化时配置writer相关参数，根本没用，也没看到哪儿有相文档和示例，这是最基础的操作啊，哎~~~~

**Comment by FishGoddess** [comment]
写文件相关的代码可以参考以下两个例子：

1. [Writer 的介绍](https://github.com/go-logit/logit/blob/57bbf0ea729ea996e2a0aa5c04be1f036bae64cb/_examples/writer.go#L40)
2. [写文件的性能压测](https://github.com/go-logit/logit/blob/57bbf0ea729ea996e2a0aa5c04be1f036bae64cb/_examples/performance_test.go#L234)

实际上 logit 里面自定义的 Writer 就是把标准库的一些接口进行拼装：

```
type Writer interface {
	io.WriteCloser
	Flusher
}
```

细节可以查看 [https://github.com/go-logit/logit/blob/57bbf0ea729ea996e2a0aa5c04be1f036bae64cb/core/writer/base.go#L35](https://github.com/go-logit/logit/blob/57bbf0ea729ea996e2a0aa5c04be1f036bae64cb/core/writer/base.go#L35)。

 所以，os.File 其实就是 Writer 的一个实现，你只需要创建一个 os.File 就可以将日志写到文件：

```
file, _ := os.OpenFile("./test.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
logger := logit.NewLogger(logit.Options().WithWriter(file, false))
logger.Info("写到文件了吗").End()
```

**Comment by Creky** [comment]
问题已解决，原因是提前关闭了file导致的
