### ISSUE TITLE
appender.Text()没必要对双引号“之类的转义啊

### ISSUE THREAD

**Issue by creky** [go-logit/logit#12]
用过很多日志框架，没见过哪个日志默认对双引号等转义的，这还浪费我时间去查找原因，日志中输出什么就是什么，你去转义干嘛，不然还叫什么日志？

另外，新版本把.End()改为.Log()纯属多此一举，直接在底层调用不行么？也没见过哪个日志框架还需要手动提交的。

base.go
`// needEscapedByte returns if value need to escape.
// The main character should be escaped is ascii less than \u0020 and \ and ".
func needEscapedByte(value byte) bool {
	return value < 32 || value == '"' || value == '\\'
}

// needEscapedRune returns if value need to escape.
// The main character should be escaped is ascii less than \u0020 and \ and ".
func needEscapedRune(value rune) bool {
	return value < utf8.RuneSelf && needEscapedByte(byte(value))
}

// appendEscapedByte appends escaped value to dst.
// The main character should be escaped is ascii less than \u0020 and \ and ".
func appendEscapedByte(dst []byte, value byte) []byte {
	switch value {
	case '"', '\\':
		return append(dst, '\\', value)
	case '\b':
		return append(dst, '\\', 'b')
	case '\f':
		return append(dst, '\\', 'f')
	case '\n':
		return append(dst, '\\', 'n')
	case '\r':
		return append(dst, '\\', 'r')
	case '\t':
		return append(dst, '\\', 't')
	default:
		// ASCii < 16 needs to add \u000 to behind.
		if value < 16 {
			return strconv.AppendInt(append(dst, '\\', 'u', '0', '0', '0'), int64(value), 16)
		}

		// ASCii in [16, 32) needs to add \u00 to behind.
		if value < 32 {
			return strconv.AppendInt(append(dst, '\\', 'u', '0', '0'), int64(value), 16)
		}

		return append(dst, value)
	}
}`

**Comment by FishGoddess** [comment]
哈，转义对 Json 类型来说必须的，不然可能会构造出一条不合法的 Json 数据串，至于 Text 类型的 appender，可以不转义，但可能会导致一条日志分了好几行（有换行符的情况下），这对于日志收集来说不友好，比如使用 filebeat 收集和切割，就需要一行一条日志，如果一条日志跨了好几行，在解析的时候其实是很难解析的（因为不知道这条日志具体跨了几行）。

其实绝大多数日志框架应该都会做转义的吧，至少对于非 console 类型的日志器，zap 和 zerolog 都是会的，不过我很想知道你说不想转义是有啥业务需要么，纯控制台输出吗 : )

你可以试试运行这个代码看看：
```
package main

import (
	"os"
	"testing"
	"time"

	"github.com/go-logit/logit"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func TestLogitLogger(t *testing.T) {
	logger := logit.NewLogger()
	logger.Info("\tfoo\nbar").String("\tfoo\nbar", "\tfoo\nbar").Log()
}

func TestZeroLogLogger(t *testing.T) {
	log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})
	log.Info().Str("\tfoo\nbar", "\tfoo\nbar").Msg("\tfoo\nbar")
}

func TestZapLogger(t *testing.T) {
	config := zap.NewProductionEncoderConfig()
	config.EncodeTime = func(t time.Time, enc zapcore.PrimitiveArrayEncoder) {
		enc.AppendString(t.Format(timeFormat))
	}
	encoder := zapcore.NewConsoleEncoder(config)
	nopWriteSyncer := zapcore.AddSync(os.Stdout)
	core := zapcore.NewCore(encoder, nopWriteSyncer, zapcore.DebugLevel)
	logger := zap.New(core)
	defer logger.Sync()

	logger.Info("\tfoo\nbar", zap.String("\tfoo\nbar", "\tfoo\nbar"))
}
```

参考：
[https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/internal/cbor/decode_stream.go#L137](https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/internal/cbor/decode_stream.go#L137)
[https://github.com/uber-go/zap/blob/7681a0abf65fb2f6474f481702922cf52d170654/zapcore/json_encoder.go#L492](https://github.com/uber-go/zap/blob/7681a0abf65fb2f6474f481702922cf52d170654/zapcore/json_encoder.go#L492)

不过你倒是提醒我了，可以搞一个 console 专用的 appender，就是为了控制台输出准备的，这时候不转义是可以的哈哈。。。

首先我解释下为啥会有 Log 这个方法，因为 appender 是序列化的形式追加数据的，每次加一个 kv 就是往一个 []byte 里面追加数据，所以我是没办法知道什么时候要停止追加，并把 []byte 写出到 writer 的，所以就需要手动调用 Log() 来结束一条日志。

zerolog 也是有一个类似 Log 的方法，叫做 Send，你可以看看源码或者文档哈，只不过它默认会在 Msg() 里面调用 Send()，看起来隐藏了而已。zap 的话底层原理也是类似，但是它的代码使用起来比较糟糕，每次都要写一遍 zap.xxx 来追加数据，并且会损失性能。

参考：
[https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/README.md?plain=1#L87](https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/README.md?plain=1#L87)

可能一开始看起来会觉得非常不顺眼难用，我也在构思 v0.5.x 的时候想过要处理掉，但是开发了一段时间之后发现要么牺牲性能，要么牺牲使用体验，而我纠结了几天之后决定，两个都不牺牲，保留 Log() 的调用。如果你觉得实在不好用，可以 fork 一份，改造成不需要 Log() 的版本，我会给你 star 的哈哈

PS：至于从 End 改成 Log 是因为我觉得 End 可读性太差，看起来很别扭，而 Log 看起来顺眼很多。

**Comment by FishGoddess** [comment]
> 用过很多日志框架，没见过哪个日志默认对双引号等转义的，这还浪费我时间去查找原因，日志中输出什么就是什么，你去转义干嘛，不然还叫什么日志？
> 
> 另外，新版本把.End()改为.Log()纯属多此一举，直接在底层调用不行么？也没见过哪个日志框架还需要手动提交的。
> 
> base.go `// needEscapedByte returns if value need to escape. // The main character should be escaped is ascii less than \u0020 and \ and ". func needEscapedByte(value byte) bool { return value < 32 || value == '"' || value == '\' }
> 
> // needEscapedRune returns if value need to escape. // The main character should be escaped is ascii less than \u0020 and \ and ". func needEscapedRune(value rune) bool { return value < utf8.RuneSelf && needEscapedByte(byte(value)) }
> 
> // appendEscapedByte appends escaped value to dst. // The main character should be escaped is ascii less than \u0020 and \ and ". func appendEscapedByte(dst []byte, value byte) []byte { switch value { case '"', '\': return append(dst, '\', value) case '\b': return append(dst, '\', 'b') case '\f': return append(dst, '\', 'f') case '\n': return append(dst, '\', 'n') case '\r': return append(dst, '\', 'r') case '\t': return append(dst, '\', 't') default: // ASCii < 16 needs to add \u000 to behind. if value < 16 { return strconv.AppendInt(append(dst, '\', 'u', '0', '0', '0'), int64(value), 16) }
> 
> ```
> 	// ASCii in [16, 32) needs to add \u00 to behind.
> 	if value < 32 {
> 		return strconv.AppendInt(append(dst, '\\', 'u', '0', '0'), int64(value), 16)
> 	}
> 
> 	return append(dst, value)
> }
> ```
> 
> }`

哈，转义对 Json 类型来说必须的，不然可能会构造出一条不合法的 Json 数据串，至于 Text 类型的 appender，可以不转义，但可能会导致一条日志分了好几行（有换行符的情况下），这对于日志收集来说不友好，比如使用 filebeat 收集和切割，就需要一行一条日志，如果一条日志跨了好几行，在解析的时候其实是很难解析的（因为不知道这条日志具体跨了几行）。

其实绝大多数日志框架应该都会做转义的吧，至少对于非 console 类型的日志器，zap 和 zerolog 都是会的，不过我很想知道你说不想转义是有啥业务需要么，纯控制台输出吗 : )

你可以试试运行这个代码看看：
```
package main

import (
	"os"
	"testing"
	"time"

	"github.com/go-logit/logit"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

func TestLogitLogger(t *testing.T) {
	logger := logit.NewLogger()
	logger.Info("\tfoo\nbar").String("\tfoo\nbar", "\tfoo\nbar").Log()
}

func TestZeroLogLogger(t *testing.T) {
	log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})
	log.Info().Str("\tfoo\nbar", "\tfoo\nbar").Msg("\tfoo\nbar")
}

func TestZapLogger(t *testing.T) {
	config := zap.NewProductionEncoderConfig()
	config.EncodeTime = func(t time.Time, enc zapcore.PrimitiveArrayEncoder) {
		enc.AppendString(t.Format(timeFormat))
	}
	encoder := zapcore.NewConsoleEncoder(config)
	nopWriteSyncer := zapcore.AddSync(os.Stdout)
	core := zapcore.NewCore(encoder, nopWriteSyncer, zapcore.DebugLevel)
	logger := zap.New(core)
	defer logger.Sync()

	logger.Info("\tfoo\nbar", zap.String("\tfoo\nbar", "\tfoo\nbar"))
}
```

参考：
[https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/internal/cbor/decode_stream.go#L137](https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/internal/cbor/decode_stream.go#L137)
[https://github.com/uber-go/zap/blob/7681a0abf65fb2f6474f481702922cf52d170654/zapcore/json_encoder.go#L492](https://github.com/uber-go/zap/blob/7681a0abf65fb2f6474f481702922cf52d170654/zapcore/json_encoder.go#L492)

不过你倒是提醒我了，可以搞一个 console 专用的 appender，就是为了控制台输出准备的，这时候不转义是可以的哈哈。。。

首先我解释下为啥会有 Log 这个方法，因为 appender 是序列化的形式追加数据的，每次加一个 kv 就是往一个 []byte 里面追加数据，所以我是没办法知道什么时候要停止追加，并把 []byte 写出到 writer 的，所以就需要手动调用 Log() 来结束一条日志。

zerolog 也是有一个类似 Log 的方法，叫做 Send，你可以看看源码或者文档哈，只不过它默认会在 Msg() 里面调用 Send()，看起来隐藏了而已。zap 的话底层原理也是类似，但是它的代码使用起来比较糟糕，每次都要写一遍 zap.xxx 来追加数据，并且会损失性能。

参考：
[https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/README.md?plain=1#L87](https://github.com/rs/zerolog/blob/c2b9d0e2defd04e1afb9712132a66681d077eb42/README.md?plain=1#L87)

可能一开始看起来会觉得非常不顺眼难用，我也在构思 v0.5.x 的时候想过要处理掉，但是开发了一段时间之后发现要么牺牲性能，要么牺牲使用体验，而我纠结了几天之后决定，两个都不牺牲，保留 Log() 的调用。如果你觉得实在不好用，可以 fork 一份，改造成不需要 Log() 的版本，我会给你 star 的哈哈

PS：至于从 End 改成 Log 是因为我觉得 End 可读性太差，看起来很别扭，而 Log 看起来顺眼很多。

**Comment by creky** [comment]
fork了，改了，也只临时改了core/appender/text.go的内容，既然都已经决定输出为txt类型了，那就应该由用户控制输出内容的转义，并且对txt类型的，实在看换行有影响也只转义\n即可。

刚fork下来，也是准备添加个配置项的，但这配置项的传递有问题，所以以简单的方式改了text.go文件。

我这日志也是写到文件的，不是控制台。

一个框架应该给用户以自由，而不是限制用户自由。

至于.Log()的问题，也只是看着影响，自己封装一层倒也挺简单。
